### ISSUE TITLE
基本文法 - データ型（コレクション）

### ISSUE THREAD

**Issue by ddd503** [ddd503/objc-basic#2]

**Comment by ddd503** [comment]
@stv-ktaguchi #2の課題に着手します。

**Comment by taguchi-k** [comment]
@ddd503 
こちら実装完了していたらプルリク作成してください。

**Comment by ddd503** [comment]
@taguchi-k 
pullrequestの作成に時間がかかってしまい、申し訳ございません。
先ほど、作成致しました。

**Comment by taguchi-k** [comment]
@ddd503
test_kadaiというプロジェクト名だと前課題と同じです。
masterにマージする際にtest_kadaiがコンフリクトを起こします。
また、コンフリクトを解消したとしてもmasterにはtest_kadaiというプロジェクトがひとつしか残りません。
課題毎に別プロジェクト名にしてください。
本課題以降の課題も同様です。

**Comment by ddd503** [comment]
@taguchi-k 
失礼致しました。
リモートリポジトリ内でのプロジェクト管理につきまして、ご質問がございます。
複数のプロジェクトを別で作り、全て「objc-basic」リポジトリにあげていくということは、マージ先の「master」ブランチも複数存在するということでしょうか。
例えば、「master1-1-2」など。
初歩的な質問で申し訳ございません。

**Comment by taguchi-k** [comment]
@ddd503 
masterブランチはひとつです。
最終的にobjc-basicリポジトリのmasterブランチに全課題のプロジェクトが存在するようになります。
下記のようなイメージです。

```
root
　├ 1.1.1のディレクトリ
│      ├プロジェクトファイル
│      └…
　├ 1.1.2のディレクトリ
│       └…
　├ 1.1.3のディレクトリ
│       └…
 …以下省略
```

**Comment by ddd503** [comment]
@taguchi-k 
大変失礼致しました。
masterからブランチを切っておらず、課題#1よりブランチを作成しておりました。
修正し、再度pullrequestを作成させて頂きました。
レビューをお願い致します。
